AF       ('1f1e6-1f1eb', 2120, 2, 1, '🇦🇫', ['AF', 'flag'], ':flag_af:', [':af:'], ('Afghanistan', 'AFG'), 'flags'),
AX       ('1f1e6-1f1fd', 2121, 2, 1, '🇦🇽', ['AX', 'flag'], ':flag_ax:', [':ax:'], ('Åland Islands', 'AXI'), 'flags'),
AL       ('1f1e6-1f1f1', 2122, 2, 1, '🇦🇱', ['AL', 'flag'], ':flag_al:', [':al:'], ('Albania', 'ALB'), 'flags'),
DZ       ('1f1e9-1f1ff', 2123, 2, 1, '🇩🇿', ['DZ', 'flag'], ':flag_dz:', [':dz:'], ('Algeria', 'DZA'), 'flags'),
AS       ('1f1e6-1f1f8', 2124, 2, 1, '🇦🇸', ['AS', 'flag'], ':flag_as:', [':as:'], ('American Samoa', 'ASM'), 'flags'),
AD       ('1f1e6-1f1e9', 2125, 2, 1, '🇦🇩', ['AD', 'flag'], ':flag_ad:', [':ad:'], ('Andorra', 'AND'), 'flags'),
AO       ('1f1e6-1f1f4', 2126, 2, 1, '🇦🇴', ['AO', 'flag'], ':flag_ao:', [':ao:'], ('Angola', 'AGO'), 'flags'),
AI       ('1f1e6-1f1ee', 2127, 2, 1, '🇦🇮', ['AI', 'flag'], ':flag_ai:', [':ai:'], ('Anguilla', 'AIA'), 'flags'),
AQ       ('1f1e6-1f1f6', 2128, 2, 1, '🇦🇶', ['AQ', 'flag'], ':flag_aq:', [':aq:'], ('Antarctica', 'ATA'), 'flags'),
AG       ('1f1e6-1f1ec', 2129, 2, 1, '🇦🇬', ['AG', 'flag'], ':flag_ag:', [':ag:'], ('Antigua and Barbuda', 'ATG'), 'flags'),
AR       ('1f1e6-1f1f7', 2130, 2, 1, '🇦🇷', ['AR', 'flag'], ':flag_ar:', [':ar:'], ('Argentina', 'ARG'), 'flags'),
AM       ('1f1e6-1f1f2', 2131, 2, 1, '🇦🇲', ['AM', 'flag'], ':flag_am:', [':am:'], ('Armenia', 'ARM'), 'flags'),
AW       ('1f1e6-1f1fc', 2132, 2, 1, '🇦🇼', ['AW', 'flag'], ':flag_aw:', [':aw:'], ('Aruba', 'ABW'), 'flags'),
AU       ('1f1e6-1f1fa', 2133, 2, 1, '🇦🇺', ['AU', 'flag'], ':flag_au:', [':au:'], ('Australia', 'AUS'), 'flags'),
AT       ('1f1e6-1f1f9', 2134, 2, 1, '🇦🇹', ['AT', 'flag'], ':flag_at:', [':at:'], ('Austria', 'AUT'), 'flags'),
AZ       ('1f1e6-1f1ff', 2135, 2, 1, '🇦🇿', ['AZ', 'flag'], ':flag_az:', [':az:'], ('Azerbaijan', 'AZE'), 'flags'),
BS       ('1f1e7-1f1f8', 2136, 2, 1, '🇧🇸', ['BS', 'flag'], ':flag_bs:', [':bs:'], ('Bahamas', 'BHS'), 'flags'),
BH       ('1f1e7-1f1ed', 2137, 2, 1, '🇧🇭', ['BH', 'flag'], ':flag_bh:', [':bh:'], ('Bahrain', 'BHR'), 'flags'),
BD       ('1f1e7-1f1e9', 2138, 2, 1, '🇧🇩', ['BD', 'flag'], ':flag_bd:', [':bd:'], ('Bangladesh', 'BGD'), 'flags'),
BB       ('1f1e7-1f1e7', 2139, 2, 1, '🇧🇧', ['BB', 'flag'], ':flag_bb:', [':bb:'], ('Barbados', 'BRB'), 'flags'),
BY       ('1f1e7-1f1fe', 2140, 2, 1, '🇧🇾', ['BY', 'flag'], ':flag_by:', [':by:'], ('Belarus', 'BLR'), 'flags'),
BE       ('1f1e7-1f1ea', 2141, 2, 1, '🇧🇪', ['BE', 'flag'], ':flag_be:', [':be:'], ('Belgium', 'BEL'), 'flags'),
BZ       ('1f1e7-1f1ff', 2142, 2, 1, '🇧🇿', ['BZ', 'flag'], ':flag_bz:', [':bz:'], ('Belize', 'BLZ'), 'flags'),
BJ       ('1f1e7-1f1ef', 2143, 2, 1, '🇧🇯', ['BJ', 'flag'], ':flag_bj:', [':bj:'], ('Benin', 'BEN'), 'flags'),
BM       ('1f1e7-1f1f2', 2144, 2, 1, '🇧🇲', ['BM', 'flag'], ':flag_bm:', [':bm:'], ('Bermuda', 'BMU'), 'flags'),
BT       ('1f1e7-1f1f9', 2145, 2, 1, '🇧🇹', ['BT', 'flag'], ':flag_bt:', [':bt:'], ('Bhutan', 'BTN'), 'flags'),
BO       ('1f1e7-1f1f4', 2146, 2, 1, '🇧🇴', ['BO', 'flag'], ':flag_bo:', [':bo:'], ('Bolivia', 'BOL'), 'flags'),
BA       ('1f1e7-1f1e6', 2147, 2, 1, '🇧🇦', ['BA', 'flag'], ':flag_ba:', [':ba:'], ('Bosnia and Herzegovina', 'BIH'), 'flags'),
BW       ('1f1e7-1f1fc', 2148, 2, 1, '🇧🇼', ['BW', 'flag'], ':flag_bw:', [':bw:'], ('Botswana', 'BWA'), 'flags'),
BR       ('1f1e7-1f1f7', 2149, 2, 1, '🇧🇷', ['BR', 'flag'], ':flag_br:', [':br:'], ('Brazil', 'BRA'), 'flags'),
IO       ('1f1ee-1f1f4', 2150, 2, 1, '🇮🇴', ['IO', 'flag'], ':flag_io:', [':io:'], ('British Indian Ocean Territory', 'IOT'), 'flags'),
VG       ('1f1fb-1f1ec', 2151, 2, 1, '🇻🇬', ['VG', 'flag'], ':flag_vg:', [':vg:'], ('British Virgin Islands', 'VGB'), 'flags'),
BN       ('1f1e7-1f1f3', 2152, 2, 1, '🇧🇳', ['BN', 'flag'], ':flag_bn:', [':bn:'], ('Brunei Darussalam', 'BRN'), 'flags'),
BG       ('1f1e7-1f1ec', 2153, 2, 1, '🇧🇬', ['BG', 'flag'], ':flag_bg:', [':bg:'], ('Bulgaria', 'BGR'), 'flags'),
BF       ('1f1e7-1f1eb', 2154, 2, 1, '🇧🇫', ['BF', 'flag'], ':flag_bf:', [':bf:'], ('Burkina Faso', 'BFA'), 'flags'),
BI       ('1f1e7-1f1ee', 2155, 2, 1, '🇧🇮', ['BI', 'flag'], ':flag_bi:', [':bi:'], ('Burundi', 'BDI'), 'flags'),
KH       ('1f1f0-1f1ed', 2156, 2, 1, '🇰🇭', ['KH', 'flag'], ':flag_kh:', [':kh:'], ('Cambodia', 'KHM'), 'flags'),
CM       ('1f1e8-1f1f2', 2157, 2, 1, '🇨🇲', ['CM', 'flag'], ':flag_cm:', [':cm:'], ('Cameroon', 'CMR'), 'flags'),
CA       ('1f1e8-1f1e6', 2158, 2, 1, '🇨🇦', ['CA', 'flag'], ':flag_ca:', [':ca:'], ('Canada', 'CAN'), 'flags'),
IC       ('1f1ee-1f1e8', 2159, 2, 1, '🇮🇨', ['IC', 'flag'], ':flag_ic:', [':ic:'], ('Canary Islands', 'TCI'), 'flags'),
CV       ('1f1e8-1f1fb', 2160, 2, 1, '🇨🇻', ['CV', 'flag'], ':flag_cv:', [':cv:'], ('Cape Verde', 'CPV'), 'flags'),
BQ       ('1f1e7-1f1f6', 2161, 2, 1, '🇧🇶', ['BQ', 'flag'], ':flag_bq:', [':bq:'], ('Bonaire', 'BES'), 'flags'),
KY       ('1f1f0-1f1fe', 2162, 2, 1, '🇰🇾', ['KY', 'flag'], ':flag_ky:', [':ky:'], ('Cayman Islands', 'CYM'), 'flags'),
CF       ('1f1e8-1f1eb', 2163, 2, 1, '🇨🇫', ['CF', 'flag'], ':flag_cf:', [':cf:'], ('Central African Republic', 'CAF'), 'flags'),
TD       ('1f1f9-1f1e9', 2164, 2, 1, '🇹🇩', ['TD', 'flag'], ':flag_td:', [':td:'], ('Chad', 'TCD'), 'flags'),
CL       ('1f1e8-1f1f1', 2165, 2, 1, '🇨🇱', ['CL', 'flag'], ':flag_cl:', [':cl:', ':chile:'], ('Chile', 'CHL'), 'flags'),
CN       ('1f1e8-1f1f3', 2166, 2, 1, '🇨🇳', ['CN', 'flag'], ':flag_cn:', [':cn:'], ('China', 'CHN'), 'flags'),
CX       ('1f1e8-1f1fd', 2167, 2, 1, '🇨🇽', ['CX', 'flag'], ':flag_cx:', [':cx:'], ('Christmas Island', 'CXR'), 'flags'),
CC       ('1f1e8-1f1e8', 2168, 2, 1, '🇨🇨', ['CC', 'flag'], ':flag_cc:', [':cc:'], ('Cocos (Keeling) Islands', 'CCK'), 'flags'),
CO       ('1f1e8-1f1f4', 2169, 2, 1, '🇨🇴', ['CO', 'flag'], ':flag_co:', [':co:'], ('Colombia', 'COL'), 'flags'),
KM       ('1f1f0-1f1f2', 2170, 2, 1, '🇰🇲', ['KM', 'flag'], ':flag_km:', [':km:'], ('Comoros', 'COM'), 'flags'),
CG       ('1f1e8-1f1ec', 2171, 2, 1, '🇨🇬', ['CG', 'flag'], ':flag_cg:', [':cg:'], ('Congo', 'COG'), 'flags'),
CD       ('1f1e8-1f1e9', 2172, 2, 1, '🇨🇩', ['CD', 'flag'], ':flag_cd:', [':cd:', ':congo:'], ('Democratic Republic of the Congo', 'COD'), 'flags'),
CK       ('1f1e8-1f1f0', 2173, 2, 1, '🇨🇰', ['CK', 'flag'], ':flag_ck:', [':ck:'], ('Cook Islands', 'COK'), 'flags'),
CR       ('1f1e8-1f1f7', 2174, 2, 1, '🇨🇷', ['CR', 'flag'], ':flag_cr:', [':cr:'], ('Costa Rica', 'CRI'), 'flags'),
CI       ('1f1e8-1f1ee', 2175, 2, 1, '🇨🇮', ['CI', 'flag'], ':flag_ci:', [':ci:'], ("Cote d'Ivoire", 'CIV'), 'flags'),
HR       ('1f1ed-1f1f7', 2176, 2, 1, '🇭🇷', ['HR', 'flag'], ':flag_hr:', [':hr:'], ('Croatia', 'HRV'), 'flags'),
CU       ('1f1e8-1f1fa', 2177, 2, 1, '🇨🇺', ['CU', 'flag'], ':flag_cu:', [':cu:'], ('Cuba', 'CUB'), 'flags'),
CW       ('1f1e8-1f1fc', 2178, 2, 1, '🇨🇼', ['CW', 'flag'], ':flag_cw:', [':cw:'], ('Curacao', 'CUW'), 'flags'),
CY       ('1f1e8-1f1fe', 2179, 2, 1, '🇨🇾', ['CY', 'flag'], ':flag_cy:', [':cy:'], ('Cyprus', 'CYP'), 'flags'),
CZ       ('1f1e8-1f1ff', 2180, 2, 1, '🇨🇿', ['CZ', 'flag'], ':flag_cz:', [':cz:'], ('Czech Republic', 'CZE'), 'flags'),
DK       ('1f1e9-1f1f0', 2181, 2, 1, '🇩🇰', ['DK', 'flag'], ':flag_dk:', [':dk:'], ('Denmark', 'DNK'), 'flags'),
DJ       ('1f1e9-1f1ef', 2182, 2, 1, '🇩🇯', ['DJ', 'flag'], ':flag_dj:', [':dj:'], ('Djibouti', 'DJI'), 'flags'),
DM       ('1f1e9-1f1f2', 2183, 2, 1, '🇩🇲', ['DM', 'flag'], ':flag_dm:', [':dm:'], ('Dominica', 'DMA'), 'flags'),
DO       ('1f1e9-1f1f4', 2184, 2, 1, '🇩🇴', ['DO', 'flag'], ':flag_do:', [':do:'], ('Dominican Republic', 'DOM'), 'flags'),
EC       ('1f1ea-1f1e8', 2185, 2, 1, '🇪🇨', ['EC', 'flag'], ':flag_ec:', [':ec:'], ('Ecuador', 'ECU'), 'flags'),
EG       ('1f1ea-1f1ec', 2186, 2, 1, '🇪🇬', ['EG', 'flag'], ':flag_eg:', [':eg:'], ('Egypt', 'EGY'), 'flags'),
SV       ('1f1f8-1f1fb', 2187, 2, 1, '🇸🇻', ['SV', 'flag'], ':flag_sv:', [':sv:'], ('El Salvador', 'SLV'), 'flags'),
GQ       ('1f1ec-1f1f6', 2188, 2, 1, '🇬🇶', ['GQ', 'flag'], ':flag_gq:', [':gq:'], ('Equatorial Guinea', 'GNQ'), 'flags'),
ER       ('1f1ea-1f1f7', 2189, 2, 1, '🇪🇷', ['ER', 'flag'], ':flag_er:', [':er:'], ('Eritrea', 'ERI'), 'flags'),
EE       ('1f1ea-1f1ea', 2190, 2, 1, '🇪🇪', ['EE', 'flag'], ':flag_ee:', [':ee:'], ('Estonia', 'EST'), 'flags'),
ET       ('1f1ea-1f1f9', 2191, 2, 1, '🇪🇹', ['ET', 'flag'], ':flag_et:', [':et:'], ('Ethiopia', 'ETH'), 'flags'),
EU       ('1f1ea-1f1f9', 2191, 2, 1, '🇪🇹', ['ET', 'flag'], ':flag_et:', [':et:'], ('Ethiopia', 'ETH'), 'flags'),
FK       ('1f1eb-1f1f0', 2193, 2, 1, '🇫🇰', ['FK', 'flag'], ':flag_fk:', [':fk:'], ('Falkland Islands (Malvinas)', 'FLK'), 'flags'),
FO       ('1f1eb-1f1f4', 2194, 2, 1, '🇫🇴', ['FO', 'flag'], ':flag_fo:', [':fo:'], ('Faroe Islands', 'FRO'), 'flags'),
FJ       ('1f1eb-1f1ef', 2195, 2, 1, '🇫🇯', ['FJ', 'flag'], ':flag_fj:', [':fj:'], ('Fiji', 'FJI'), 'flags'),
FI       ('1f1eb-1f1ee', 2196, 2, 1, '🇫🇮', ['FI', 'flag'], ':flag_fi:', [':fi:'], ('Finland', 'FIN'), 'flags'),
FR       ('1f1eb-1f1f7', 2197, 2, 1, '🇫🇷', ['FR', 'flag'], ':flag_fr:', [':fr:'], ('France', 'FRA'), 'flags'),
GF       ('1f1ec-1f1eb', 2198, 2, 1, '🇬🇫', ['GF', 'flag'], ':flag_gf:', [':gf:'], ('French Guiana', 'GUF'), 'flags'),
PF       ('1f1f5-1f1eb', 2199, 2, 1, '🇵🇫', ['PF', 'flag'], ':flag_pf:', [':pf:'], ('French Polynesia', 'PYF'), 'flags'),
TF       ('1f1f9-1f1eb', 2200, 2, 1, '🇹🇫', ['TF', 'flag'], ':flag_tf:', [':tf:'], ('French Southern Territories', 'ATF'), 'flags'),
GA       ('1f1ec-1f1e6', 2201, 2, 1, '🇬🇦', ['GA', 'flag'], ':flag_ga:', [':ga:'], ('Gabon', 'GAB'), 'flags'),
GM       ('1f1ec-1f1f2', 2202, 2, 1, '🇬🇲', ['GM', 'flag'], ':flag_gm:', [':gm:'], ('Gambia', 'GMB'), 'flags'),
GE       ('1f1ec-1f1ea', 2203, 2, 1, '🇬🇪', ['GE', 'flag'], ':flag_ge:', [':ge:'], ('Georgia', 'GEO'), 'flags'),
DE       ('1f1e9-1f1ea', 2204, 2, 1, '🇩🇪', ['DE', 'flag'], ':flag_de:', [':de:'], ('Germany', 'DEU'), 'flags'),
GH       ('1f1ec-1f1ed', 2205, 2, 1, '🇬🇭', ['GH', 'flag'], ':flag_gh:', [':gh:'], ('Ghana', 'GHA'), 'flags'),
GI       ('1f1ec-1f1ee', 2206, 2, 1, '🇬🇮', ['GI', 'flag'], ':flag_gi:', [':gi:'], ('Gibraltar', 'GIB'), 'flags'),
GR       ('1f1ec-1f1f7', 2207, 2, 1, '🇬🇷', ['GR', 'flag'], ':flag_gr:', [':gr:'], ('Greece', 'GRC'), 'flags'),
GL       ('1f1ec-1f1f1', 2208, 2, 1, '🇬🇱', ['GL', 'flag'], ':flag_gl:', [':gl:'], ('Greenland', 'GRL'), 'flags'),
GD       ('1f1ec-1f1e9', 2209, 2, 1, '🇬🇩', ['GD', 'flag'], ':flag_gd:', [':gd:'], ('Grenada', 'GRD'), 'flags'),
GP       ('1f1ec-1f1f5', 2210, 2, 1, '🇬🇵', ['GP', 'flag'], ':flag_gp:', [':gp:'], ('Guadeloupe', 'GLP'), 'flags'),
GU       ('1f1ec-1f1fa', 2211, 2, 1, '🇬🇺', ['GU', 'flag'], ':flag_gu:', [':gu:'], ('Guam', 'GUM'), 'flags'),
GT       ('1f1ec-1f1f9', 2212, 2, 1, '🇬🇹', ['GT', 'flag'], ':flag_gt:', [':gt:'], ('Guatemala', 'GTM'), 'flags'),
GG       ('1f1ec-1f1ec', 2213, 2, 1, '🇬🇬', ['GG', 'flag'], ':flag_gg:', [':gg:'], ('Guernsey', 'GGY'), 'flags'),
GN       ('1f1ec-1f1f3', 2214, 2, 1, '🇬🇳', ['GN', 'flag'], ':flag_gn:', [':gn:'], ('Guinea', 'GIN'), 'flags'),
GW       ('1f1ec-1f1fc', 2215, 2, 1, '🇬🇼', ['GW', 'flag'], ':flag_gw:', [':gw:'], ('Guinea-Bissau', 'GNB'), 'flags'),
GY       ('1f1ec-1f1fe', 2216, 2, 1, '🇬🇾', ['GY', 'flag'], ':flag_gy:', [':gy:'], ('Guyana', 'GUY'), 'flags'),
HT       ('1f1ed-1f1f9', 2217, 2, 1, '🇭🇹', ['HT', 'flag'], ':flag_ht:', [':ht:'], ('Haiti', 'HTI'), 'flags'),
HN       ('1f1ed-1f1f3', 2218, 2, 1, '🇭🇳', ['HN', 'flag'], ':flag_hn:', [':hn:'], ('Honduras', 'HND'), 'flags'),
HK       ('1f1ed-1f1f0', 2219, 2, 1, '🇭🇰', ['HK', 'flag'], ':flag_hk:', [':hk:'], ('Hong Kong', 'HKG'), 'flags'),
HU       ('1f1ed-1f1fa', 2220, 2, 1, '🇭🇺', ['HU', 'flag'], ':flag_hu:', [':hu:'], ('Hungary', 'HUN'), 'flags'),
IS       ('1f1ee-1f1f8', 2221, 2, 1, '🇮🇸', ['IS', 'flag'], ':flag_is:', [':is:'], ('Iceland', 'ISL'), 'flags'),
IN       ('1f1ee-1f1f3', 2222, 2, 1, '🇮🇳', ['IN', 'flag'], ':flag_in:', [':in:'], ('India', 'IND'), 'flags'),
ID       ('1f1ee-1f1e9', 2223, 2, 1, '🇮🇩', ['ID', 'flag'], ':flag_id:', [':id:'], ('Indonesia', 'IDN'), 'flags'),
IR       ('1f1ee-1f1f7', 2224, 2, 1, '🇮🇷', ['IR', 'flag'], ':flag_ir:', [':ir:'], ('Iran, Islamic Republic of', 'IRN'), 'flags'),
IQ       ('1f1ee-1f1f6', 2225, 2, 1, '🇮🇶', ['IQ', 'flag'], ':flag_iq:', [':iq:'], ('Iraq', 'IRQ'), 'flags'),
IE       ('1f1ee-1f1ea', 2226, 2, 1, '🇮🇪', ['IE', 'flag'], ':flag_ie:', [':ie:'], ('Ireland', 'IRL'), 'flags'),
IM       ('1f1ee-1f1f2', 2227, 2, 1, '🇮🇲', ['IM', 'flag'], ':flag_im:', [':im:'], ('Isle of Man', 'IMN'), 'flags'),
IL       ('1f1ee-1f1f1', 2228, 2, 1, '🇮🇱', ['IL', 'flag'], ':flag_il:', [':il:'], ('Israel', 'ISR'), 'flags'),
IT       ('1f1ee-1f1f9', 2229, 2, 1, '🇮🇹', ['IT', 'flag'], ':flag_it:', [':it:'], ('Italy', 'ITA'), 'flags'),
JM       ('1f1ef-1f1f2', 2230, 2, 1, '🇯🇲', ['JM', 'flag'], ':flag_jm:', [':jm:'], ('Jamaica', 'JAM'), 'flags'),
JP       ('1f1ef-1f1f5', 2231, 2, 1, '🇯🇵', ['JP', 'flag'], ':flag_jp:', [':jp:'], ('Japan', 'JPN'), 'flags'),
JE       ('1f1ef-1f1ea', 2233, 2, 1, '🇯🇪', ['JE', 'flag'], ':flag_je:', [':je:'], ('Jersey', 'JEY'), 'flags'),
JO       ('1f1ef-1f1f4', 2234, 2, 1, '🇯🇴', ['JO', 'flag'], ':flag_jo:', [':jo:'], ('Jordan', 'JOR'), 'flags'),
KZ       ('1f1f0-1f1ff', 2235, 2, 1, '🇰🇿', ['KZ', 'flag'], ':flag_kz:', [':kz:'], ('Kazakhstan', 'KAZ'), 'flags'),
KE       ('1f1f0-1f1ea', 2236, 2, 1, '🇰🇪', ['KE', 'flag'], ':flag_ke:', [':ke:'], ('Kenya', 'KEN'), 'flags'),
KI       ('1f1f0-1f1ee', 2237, 2, 1, '🇰🇮', ['KI', 'flag'], ':flag_ki:', [':ki:'], ('Kiribati', 'KIR'), 'flags'),
XK       ('1f1f0-1f1ee', 2237, 2, 1, '🇰🇮', ['KI', 'flag'], ':flag_ki:', [':ki:'], ('Kiribati', 'KIR'), 'flags'),
KW       ('1f1f0-1f1fc', 2239, 2, 1, '🇰🇼', ['KW', 'flag'], ':flag_kw:', [':kw:'], ('Kuwait', 'KWT'), 'flags'),
KG       ('1f1f0-1f1ec', 2240, 2, 1, '🇰🇬', ['KG', 'flag'], ':flag_kg:', [':kg:'], ('Kyrgyzstan', 'KGZ'), 'flags'),
LA       ('1f1f1-1f1e6', 2241, 2, 1, '🇱🇦', ['LA', 'flag'], ':flag_la:', [':la:'], ("Lao People's Democratic Republic", 'LAO'), 'flags'),
LV       ('1f1f1-1f1fb', 2242, 2, 1, '🇱🇻', ['LV', 'flag'], ':flag_lv:', [':lv:'], ('Latvia', 'LVA'), 'flags'),
LB       ('1f1f1-1f1e7', 2243, 2, 1, '🇱🇧', ['LB', 'flag'], ':flag_lb:', [':lb:'], ('Lebanon', 'LBN'), 'flags'),
LS       ('1f1f1-1f1f8', 2244, 2, 1, '🇱🇸', ['LS', 'flag'], ':flag_ls:', [':ls:'], ('Lesotho', 'LSO'), 'flags'),
LR       ('1f1f1-1f1f7', 2245, 2, 1, '🇱🇷', ['LR', 'flag'], ':flag_lr:', [':lr:'], ('Liberia', 'LBR'), 'flags'),
LY       ('1f1f1-1f1fe', 2246, 2, 1, '🇱🇾', ['LY', 'flag'], ':flag_ly:', [':ly:'], ('Libya', 'LBY'), 'flags'),
LI       ('1f1f1-1f1ee', 2247, 2, 1, '🇱🇮', ['LI', 'flag'], ':flag_li:', [':li:'], ('Liechtenstein', 'LIE'), 'flags'),
LT       ('1f1f1-1f1f9', 2248, 2, 1, '🇱🇹', ['LT', 'flag'], ':flag_lt:', [':lt:'], ('Lithuania', 'LTU'), 'flags'),
LU       ('1f1f1-1f1fa', 2249, 2, 1, '🇱🇺', ['LU', 'flag'], ':flag_lu:', [':lu:'], ('Luxembourg', 'LUX'), 'flags'),
MO       ('1f1f2-1f1f4', 2250, 2, 1, '🇲🇴', ['MO', 'flag'], ':flag_mo:', [':mo:'], ('Macao', 'MAC'), 'flags'),
MK       ('1f1f2-1f1f0', 2251, 2, 1, '🇲🇰', ['MK', 'flag'], ':flag_mk:', [':mk:'], ('Macedonia, the Former Yugoslav Republic of', 'MKD'), 'flags'),
MG       ('1f1f2-1f1ec', 2252, 2, 1, '🇲🇬', ['MG', 'flag'], ':flag_mg:', [':mg:'], ('Madagascar', 'MDG'), 'flags'),
MW       ('1f1f2-1f1fc', 2253, 2, 1, '🇲🇼', ['MW', 'flag'], ':flag_mw:', [':mw:'], ('Malawi', 'MWI'), 'flags'),
MY       ('1f1f2-1f1fe', 2254, 2, 1, '🇲🇾', ['MY', 'flag'], ':flag_my:', [':my:'], ('Malaysia', 'MYS'), 'flags'),
MV       ('1f1f2-1f1fb', 2255, 2, 1, '🇲🇻', ['MV', 'flag'], ':flag_mv:', [':mv:'], ('Maldives', 'MDV'), 'flags'),
ML       ('1f1f2-1f1f1', 2256, 2, 1, '🇲🇱', ['ML', 'flag'], ':flag_ml:', [':ml:'], ('Mali', 'MLI'), 'flags'),
MT       ('1f1f2-1f1f9', 2257, 2, 1, '🇲🇹', ['MT', 'flag'], ':flag_mt:', [':mt:'], ('Malta', 'MLT'), 'flags'),
MH       ('1f1f2-1f1ed', 2258, 2, 1, '🇲🇭', ['MH', 'flag'], ':flag_mh:', [':mh:'], ('Marshall Islands', 'MHL'), 'flags'),
MQ       ('1f1f2-1f1f6', 2259, 2, 1, '🇲🇶', ['MQ', 'flag'], ':flag_mq:', [':mq:'], ('Martinique', 'MTQ'), 'flags'),
MR       ('1f1f2-1f1f7', 2260, 2, 1, '🇲🇷', ['MR', 'flag'], ':flag_mr:', [':mr:'], ('Mauritania', 'MRT'), 'flags'),
MU       ('1f1f2-1f1fa', 2261, 2, 1, '🇲🇺', ['MU', 'flag'], ':flag_mu:', [':mu:'], ('Mauritius', 'MUS'), 'flags'),
YT       ('1f1fe-1f1f9', 2262, 2, 1, '🇾🇹', ['YT', 'flag'], ':flag_yt:', [':yt:'], ('Mayotte', 'MYT'), 'flags'),
MX       ('1f1f2-1f1fd', 2263, 2, 1, '🇲🇽', ['MX', 'flag'], ':flag_mx:', [':mx:'], ('Mexico', 'MEX'), 'flags'),
FM       ('1f1eb-1f1f2', 2264, 2, 1, '🇫🇲', ['FM', 'flag'], ':flag_fm:', [':fm:'], ('Micronesia, Federated States of', 'FSM'), 'flags'),
MD       ('1f1f2-1f1e9', 2265, 2, 1, '🇲🇩', ['MD', 'flag'], ':flag_md:', [':md:'], ('Moldova, Republic of', 'MDA'), 'flags'),
MC       ('1f1f2-1f1e8', 2266, 2, 1, '🇲🇨', ['MC', 'flag'], ':flag_mc:', [':mc:'], ('Monaco', 'MCO'), 'flags'),
MN       ('1f1f2-1f1f3', 2267, 2, 1, '🇲🇳', ['MN', 'flag'], ':flag_mn:', [':mn:'], ('Mongolia', 'MNG'), 'flags'),
ME       ('1f1f2-1f1ea', 2268, 2, 1, '🇲🇪', ['ME', 'flag'], ':flag_me:', [':me:'], ('Montenegro', 'MNE'), 'flags'),
MS       ('1f1f2-1f1f8', 2269, 2, 1, '🇲🇸', ['MS', 'flag'], ':flag_ms:', [':ms:'], ('Montserrat', 'MSR'), 'flags'),
MA       ('1f1f2-1f1e6', 2270, 2, 1, '🇲🇦', ['MA', 'flag'], ':flag_ma:', [':ma:'], ('Morocco', 'MAR'), 'flags'),
MZ       ('1f1f2-1f1ff', 2271, 2, 1, '🇲🇿', ['MZ', 'flag'], ':flag_mz:', [':mz:'], ('Mozambique', 'MOZ'), 'flags'),
MM       ('1f1f2-1f1f2', 2272, 2, 1, '🇲🇲', ['MM', 'flag'], ':flag_mm:', [':mm:'], ('Myanmar', 'MMR'), 'flags'),
NA       ('1f1f3-1f1e6', 2273, 2, 1, '🇳🇦', ['NA', 'flag'], ':flag_na:', [':na:'], ('Namibia', 'NAM'), 'flags'),
NR       ('1f1f3-1f1f7', 2274, 2, 1, '🇳🇷', ['NR', 'flag'], ':flag_nr:', [':nr:'], ('Nauru', 'NRU'), 'flags'),
NP       ('1f1f3-1f1f5', 2275, 2, 1, '🇳🇵', ['NP', 'flag'], ':flag_np:', [':np:'], ('Nepal', 'NPL'), 'flags'),
NL       ('1f1f3-1f1f1', 2276, 2, 1, '🇳🇱', ['NL', 'flag'], ':flag_nl:', [':nl:'], ('Netherlands', 'NLD'), 'flags'),
NC       ('1f1f3-1f1e8', 2277, 2, 1, '🇳🇨', ['NC', 'flag'], ':flag_nc:', [':nc:'], ('New Caledonia', 'NCL'), 'flags'),
NZ       ('1f1f3-1f1ff', 2278, 2, 1, '🇳🇿', ['NZ', 'flag'], ':flag_nz:', [':nz:'], ('New Zealand', 'NZL'), 'flags'),
NI       ('1f1f3-1f1ee', 2279, 2, 1, '🇳🇮', ['NI', 'flag'], ':flag_ni:', [':ni:'], ('Nicaragua', 'NIC'), 'flags'),
NE       ('1f1f3-1f1ea', 2280, 2, 1, '🇳🇪', ['NE', 'flag'], ':flag_ne:', [':ne:'], ('Niger', 'NER'), 'flags'),
NG       ('1f1f3-1f1ec', 2281, 2, 1, '🇳🇬', ['NG', 'flag'], ':flag_ng:', [':ng:'], ('Nigeria', 'NGA'), 'flags'),
NU       ('1f1f3-1f1fa', 2282, 2, 1, '🇳🇺', ['NU', 'flag'], ':flag_nu:', [':nu:'], ('Niue', 'NIU'), 'flags'),
NF       ('1f1f3-1f1eb', 2283, 2, 1, '🇳🇫', ['NF', 'flag'], ':flag_nf:', [':nf:'], ('Norfolk Island', 'NFK'), 'flags'),
KP       ('1f1f0-1f1f5', 2284, 2, 1, '🇰🇵', ['KP', 'flag'], ':flag_kp:', [':kp:'], ("Korea, Democratic People's Republic of", 'PRK'), 'flags'),
MP       ('1f1f2-1f1f5', 2285, 2, 1, '🇲🇵', ['MP', 'flag'], ':flag_mp:', [':mp:'], ('Northern Mariana Islands', 'MNP'), 'flags'),
NO       ('1f1f3-1f1f4', 2286, 2, 1, '🇳🇴', ['NO', 'flag'], ':flag_no:', [':no:'], ('Norway', 'NOR'), 'flags'),
OM       ('1f1f4-1f1f2', 2287, 2, 1, '🇴🇲', ['OM', 'flag'], ':flag_om:', [':om:'], ('Oman', 'OMN'), 'flags'),
PK       ('1f1f5-1f1f0', 2288, 2, 1, '🇵🇰', ['PK', 'flag'], ':flag_pk:', [':pk:'], ('Pakistan', 'PAK'), 'flags'),
PW       ('1f1f5-1f1fc', 2289, 2, 1, '🇵🇼', ['PW', 'flag'], ':flag_pw:', [':pw:'], ('Palau', 'PLW'), 'flags'),
PS       ('1f1f5-1f1f8', 2290, 2, 1, '🇵🇸', ['PS', 'flag'], ':flag_ps:', [':ps:'], ('Palestine, State of', 'PSE'), 'flags'),
PA       ('1f1f5-1f1e6', 2291, 2, 1, '🇵🇦', ['PA', 'flag'], ':flag_pa:', [':pa:'], ('Panama', 'PAN'), 'flags'),
PG       ('1f1f5-1f1ec', 2292, 2, 1, '🇵🇬', ['PG', 'flag'], ':flag_pg:', [':pg:'], ('Papua New Guinea', 'PNG'), 'flags'),
PY       ('1f1f5-1f1fe', 2293, 2, 1, '🇵🇾', ['PY', 'flag'], ':flag_py:', [':py:'], ('Paraguay', 'PRY'), 'flags'),
PE       ('1f1f5-1f1ea', 2294, 2, 1, '🇵🇪', ['PE', 'flag'], ':flag_pe:', [':pe:'], ('Peru', 'PER'), 'flags'),
PH       ('1f1f5-1f1ed', 2295, 2, 1, '🇵🇭', ['PH', 'flag'], ':flag_ph:', [':ph:'], ('Philippines', 'PHL'), 'flags'),
PN       ('1f1f5-1f1f3', 2296, 2, 1, '🇵🇳', ['PN', 'flag'], ':flag_pn:', [':pn:'], ('Pitcairn', 'PCN'), 'flags'),
PL       ('1f1f5-1f1f1', 2297, 2, 1, '🇵🇱', ['PL', 'flag'], ':flag_pl:', [':pl:'], ('Poland', 'POL'), 'flags'),
PT       ('1f1f5-1f1f9', 2298, 2, 1, '🇵🇹', ['PT', 'flag'], ':flag_pt:', [':pt:'], ('Portugal', 'PRT'), 'flags'),
PR       ('1f1f5-1f1f7', 2299, 2, 1, '🇵🇷', ['PR', 'flag'], ':flag_pr:', [':pr:'], ('Puerto Rico', 'PRI'), 'flags'),
QA       ('1f1f6-1f1e6', 2300, 2, 1, '🇶🇦', ['QA', 'flag'], ':flag_qa:', [':qa:'], ('Qatar', 'QAT'), 'flags'),
RE       ('1f1f7-1f1ea', 2301, 2, 1, '🇷🇪', ['RE', 'flag'], ':flag_re:', [':re:'], ('Reunion', 'REU'), 'flags'),
RO       ('1f1f7-1f1f4', 2302, 2, 1, '🇷🇴', ['RO', 'flag'], ':flag_ro:', [':ro:'], ('Romania', 'ROU'), 'flags'),
RU       ('1f1f7-1f1fa', 2303, 2, 1, '🇷🇺', ['RU', 'flag'], ':flag_ru:', [':ru:'], ('Russian Federation', 'RUS'), 'flags'),
RW       ('1f1f7-1f1fc', 2304, 2, 1, '🇷🇼', ['RW', 'flag'], ':flag_rw:', [':rw:'], ('Rwanda', 'RWA'), 'flags'),
WS       ('1f1fc-1f1f8', 2305, 2, 1, '🇼🇸', ['WS', 'flag'], ':flag_ws:', [':ws:'], ('Samoa', 'WSM'), 'flags'),
SM       ('1f1f8-1f1f2', 2306, 2, 1, '🇸🇲', ['SM', 'flag'], ':flag_sm:', [':sm:'], ('San Marino', 'SMR'), 'flags'),
ST       ('1f1f8-1f1f9', 2307, 2, 1, '🇸🇹', ['ST', 'flag'], ':flag_st:', [':st:'], ('Sao Tome and Principe', 'STP'), 'flags'),
SA       ('1f1f8-1f1e6', 2308, 2, 1, '🇸🇦', ['SA', 'flag'], ':flag_sa:', [':sa:', ':saudiarabia:', ':saudi:'], ('Saudi Arabia', 'SAU'), 'flags'),
SN       ('1f1f8-1f1f3', 2309, 2, 1, '🇸🇳', ['SN', 'flag'], ':flag_sn:', [':sn:'], ('Senegal', 'SEN'), 'flags'),
RS       ('1f1f7-1f1f8', 2310, 2, 1, '🇷🇸', ['RS', 'flag'], ':flag_rs:', [':rs:'], ('Serbia', 'SRB'), 'flags'),
SC       ('1f1f8-1f1e8', 2311, 2, 1, '🇸🇨', ['SC', 'flag'], ':flag_sc:', [':sc:'], ('Seychelles', 'SYC'), 'flags'),
SL       ('1f1f8-1f1f1', 2312, 2, 1, '🇸🇱', ['SL', 'flag'], ':flag_sl:', [':sl:'], ('Sierra Leone', 'SLE'), 'flags'),
SG       ('1f1f8-1f1ec', 2313, 2, 1, '🇸🇬', ['SG', 'flag'], ':flag_sg:', [':sg:'], ('Singapore', 'SGP'), 'flags'),
SX       ('1f1f8-1f1fd', 2314, 2, 1, '🇸🇽', ['SX', 'flag'], ':flag_sx:', [':sx:'], ('Sint Maarten (Dutch part)', 'SXM'), 'flags'),
SK       ('1f1f8-1f1f0', 2315, 2, 1, '🇸🇰', ['SK', 'flag'], ':flag_sk:', [':sk:'], ('Slovakia', 'SVK'), 'flags'),
SI       ('1f1f8-1f1ee', 2316, 2, 1, '🇸🇮', ['SI', 'flag'], ':flag_si:', [':si:'], ('Slovenia', 'SVN'), 'flags'),
GS       ('1f1ec-1f1f8', 2317, 2, 1, '🇬🇸', ['GS', 'flag'], ':flag_gs:', [':gs:'], ('South Georgia and the South Sandwich Islands', 'SGS'), 'flags'),
SB       ('1f1f8-1f1e7', 2318, 2, 1, '🇸🇧', ['SB', 'flag'], ':flag_sb:', [':sb:'], ('Solomon Islands', 'SLB'), 'flags'),
SO       ('1f1f8-1f1f4', 2319, 2, 1, '🇸🇴', ['SO', 'flag'], ':flag_so:', [':so:'], ('Somalia', 'SOM'), 'flags'),
ZA       ('1f1ff-1f1e6', 2320, 2, 1, '🇿🇦', ['ZA', 'flag'], ':flag_za:', [':za:'], ('South Africa', 'ZAF'), 'flags'),
KR       ('1f1f0-1f1f7', 2321, 2, 1, '🇰🇷', ['KR', 'flag'], ':flag_kr:', [':kr:'], ('Korea, Republic of', 'KOR'), 'flags'),
SS       ('1f1f8-1f1f8', 2322, 2, 1, '🇸🇸', ['SS', 'flag'], ':flag_ss:', [':ss:'], ('South Sudan', 'SSD'), 'flags'),
ES       ('1f1ea-1f1f8', 2323, 2, 1, '🇪🇸', ['ES', 'flag'], ':flag_es:', [':es:'], ('Spain', 'ESP'), 'flags'),
LK       ('1f1f1-1f1f0', 2324, 2, 1, '🇱🇰', ['LK', 'flag'], ':flag_lk:', [':lk:'], ('Sri Lanka', 'LKA'), 'flags'),
BL       ('1f1e7-1f1f1', 2325, 2, 1, '🇧🇱', ['BL', 'flag'], ':flag_bl:', [':bl:'], ('Saint Barthelemy', 'BLM'), 'flags'),
SH       ('1f1f8-1f1ed', 2326, 2, 1, '🇸🇭', ['SH', 'flag'], ':flag_sh:', [':sh:'], ('Saint Helena', 'SHN'), 'flags'),
KN       ('1f1f0-1f1f3', 2327, 2, 1, '🇰🇳', ['KN', 'flag'], ':flag_kn:', [':kn:'], ('Saint Kitts and Nevis', 'KNA'), 'flags'),
LC       ('1f1f1-1f1e8', 2328, 2, 1, '🇱🇨', ['LC', 'flag'], ':flag_lc:', [':lc:'], ('Saint Lucia', 'LCA'), 'flags'),
PM       ('1f1f5-1f1f2', 2329, 2, 1, '🇵🇲', ['PM', 'flag'], ':flag_pm:', [':pm:'], ('Saint Pierre and Miquelon', 'SPM'), 'flags'),
VC       ('1f1fb-1f1e8', 2330, 2, 1, '🇻🇨', ['VC', 'flag'], ':flag_vc:', [':vc:'], ('Saint Vincent and the Grenadines', 'VCT'), 'flags'),
SD       ('1f1f8-1f1e9', 2331, 2, 1, '🇸🇩', ['SD', 'flag'], ':flag_sd:', [':sd:'], ('Sudan', 'SDN'), 'flags'),
SR       ('1f1f8-1f1f7', 2332, 2, 1, '🇸🇷', ['SR', 'flag'], ':flag_sr:', [':sr:'], ('Suriname', 'SUR'), 'flags'),
SZ       ('1f1f8-1f1ff', 2333, 2, 1, '🇸🇿', ['SZ', 'flag'], ':flag_sz:', [':sz:'], ('Swaziland', 'SWZ'), 'flags'),
SE       ('1f1f8-1f1ea', 2334, 2, 1, '🇸🇪', ['SE', 'flag'], ':flag_se:', [':se:'], ('Sweden', 'SWE'), 'flags'),
CH       ('1f1e8-1f1ed', 2335, 2, 1, '🇨🇭', ['CH', 'flag'], ':flag_ch:', [':ch:'], ('Switzerland', 'CHE'), 'flags'),
SY       ('1f1f8-1f1fe', 2336, 2, 1, '🇸🇾', ['SY', 'flag'], ':flag_sy:', [':sy:'], ('Syrian Arab Republic', 'SYR'), 'flags'),
TW       ('1f1f9-1f1fc', 2337, 2, 1, '🇹🇼', ['TW', 'flag'], ':flag_tw:', [':tw:'], ('Taiwan, Province of China', 'TWN'), 'flags'),
TJ       ('1f1f9-1f1ef', 2338, 2, 1, '🇹🇯', ['TJ', 'flag'], ':flag_tj:', [':tj:'], ('Tajikistan', 'TJK'), 'flags'),
TZ       ('1f1f9-1f1ff', 2339, 2, 1, '🇹🇿', ['TZ', 'flag'], ':flag_tz:', [':tz:'], ('United Republic of Tanzania', 'TZA'), 'flags'),
TH       ('1f1f9-1f1ed', 2340, 2, 1, '🇹🇭', ['TH', 'flag'], ':flag_th:', [':th:'], ('Thailand', 'THA'), 'flags'),
TL       ('1f1f9-1f1f1', 2341, 2, 1, '🇹🇱', ['TL', 'flag'], ':flag_tl:', [':tl:'], ('Timor-Leste', 'TLS'), 'flags'),
TG       ('1f1f9-1f1ec', 2342, 2, 1, '🇹🇬', ['TG', 'flag'], ':flag_tg:', [':tg:'], ('Togo', 'TGO'), 'flags'),
TK       ('1f1f9-1f1f0', 2343, 2, 1, '🇹🇰', ['TK', 'flag'], ':flag_tk:', [':tk:'], ('Tokelau', 'TKL'), 'flags'),
TO       ('1f1f9-1f1f4', 2344, 2, 1, '🇹🇴', ['TO', 'flag'], ':flag_to:', [':to:'], ('Tonga', 'TON'), 'flags'),
TT       ('1f1f9-1f1f9', 2345, 2, 1, '🇹🇹', ['TT', 'flag'], ':flag_tt:', [':tt:'], ('Trinidad and Tobago', 'TTO'), 'flags'),
TN       ('1f1f9-1f1f3', 2346, 2, 1, '🇹🇳', ['TN', 'flag'], ':flag_tn:', [':tn:'], ('Tunisia', 'TUN'), 'flags'),
TR       ('1f1f9-1f1f7', 2347, 2, 1, '🇹🇷', ['TR', 'flag'], ':flag_tr:', [':tr:'], ('Turkey', 'TUR'), 'flags'),
TM       ('1f1f9-1f1f2', 2348, 2, 1, '🇹🇲', ['TM', 'flag'], ':flag_tm:', [':tm:', ':turkmenistan:'], ('Turkmenistan', 'TKM'), 'flags'),
TC       ('1f1f9-1f1e8', 2349, 2, 1, '🇹🇨', ['TC', 'flag'], ':flag_tc:', [':tc:'], ('Turks and Caicos Islands', 'TCA'), 'flags'),
TV       ('1f1f9-1f1fb', 2350, 2, 1, '🇹🇻', ['TV', 'flag'], ':flag_tv:', [':tv:', ':tuvalu:'], ('Tuvalu', 'TUV'), 'flags'),
VI       ('1f1fb-1f1ee', 2351, 2, 1, '🇻🇮', ['VI', 'flag'], ':flag_vi:', [':vi:'], ('US Virgin Islands', 'VIR'), 'flags'),
UG       ('1f1fa-1f1ec', 2352, 2, 1, '🇺🇬', ['UG', 'flag'], ':flag_ug:', [':ug:'], ('Uganda', 'UGA'), 'flags'),
UA       ('1f1fa-1f1e6', 2353, 2, 1, '🇺🇦', ['UA', 'flag'], ':flag_ua:', [':ua:'], ('Ukraine', 'UKR'), 'flags'),
AE       ('1f1e6-1f1ea', 2354, 2, 1, '🇦🇪', ['AE', 'flag'], ':flag_ae:', [':ae:'], ('United Arab Emirates', 'ARE'), 'flags'),
GB       ('1f1ec-1f1e7', 2355, 2, 1, '🇬🇧', ['GB', 'flag'], ':flag_gb:', [':gb:'], ('United Kingdom', 'GBR'), 'flags'),
US       ('1f1fa-1f1f8', 2356, 2, 1, '🇺🇸', ['US', 'flag'], ':flag_us:', [':us:'], ('United States', 'USA'), 'flags'),
UY       ('1f1fa-1f1fe', 2357, 2, 1, '🇺🇾', ['UY', 'flag'], ':flag_uy:', [':uy:'], ('Uruguay', 'URY'), 'flags'),
UZ       ('1f1fa-1f1ff', 2358, 2, 1, '🇺🇿', ['UZ', 'flag'], ':flag_uz:', [':uz:'], ('Uzbekistan', 'UZB'), 'flags'),
VU       ('1f1fb-1f1fa', 2359, 2, 1, '🇻🇺', ['VU', 'flag'], ':flag_vu:', [':vu:'], ('Vanuatu', 'VUT'), 'flags'),
VA       ('1f1fb-1f1e6', 2360, 2, 1, '🇻🇦', ['VA', 'flag'], ':flag_va:', [':va:'], ('Holy See (Vatican City State)', 'VAT'), 'flags'),
VE       ('1f1fb-1f1ea', 2361, 2, 1, '🇻🇪', ['VE', 'flag'], ':flag_ve:', [':ve:'], ('Venezuela', 'VEN'), 'flags'),
VN       ('1f1fb-1f1f3', 2362, 2, 1, '🇻🇳', ['VN', 'flag'], ':flag_vn:', [':vn:'], ('Viet Nam', 'VNM'), 'flags'),
WF       ('1f1fc-1f1eb', 2363, 2, 1, '🇼🇫', ['WF', 'flag'], ':flag_wf:', [':wf:'], ('Wallis and Futuna', 'WLF'), 'flags'),
EH       ('1f1ea-1f1ed', 2364, 2, 1, '🇪🇭', ['EH', 'flag'], ':flag_eh:', [':eh:'], ('Western Sahara', 'ESH'), 'flags'),
YE       ('1f1fe-1f1ea', 2365, 2, 1, '🇾🇪', ['YE', 'flag'], ':flag_ye:', [':ye:'], ('Yemen', 'YEM'), 'flags'),
ZM       ('1f1ff-1f1f2', 2366, 2, 1, '🇿🇲', ['ZM', 'flag'], ':flag_zm:', [':zm:'], ('Zambia', 'ZMB'), 'flags'),
ZW       ('1f1ff-1f1fc', 2367, 2, 1, '🇿🇼', ['ZW', 'flag'], ':flag_zw:', [':zw:'], ('Zimbabwe', 'ZWE'), 'flags'),
AC       ('1f1ff-1f1fc', 2367, 2, 1, '🇿🇼', ['ZW', 'flag'], ':flag_zw:', [':zw:'], ('Zimbabwe', 'ZWE'), 'flags'),
TA       ('1f1ff-1f1fc', 2367, 2, 1, '🇿🇼', ['ZW', 'flag'], ':flag_zw:', [':zw:'], ('Zimbabwe', 'ZWE'), 'flags'),
BV       ('1f1e7-1f1fb', 2370, 2, 1, '🇧🇻', ['BV', 'flag'], ':flag_bv:', [':bv:'], ('Bouvet Island', 'BVT'), 'flags'),
HM       ('1f1ed-1f1f2', 2371, 2, 1, '🇭🇲', ['HM', 'flag'], ':flag_hm:', [':hm:'], ('Heard Island and McDonald Mcdonald Islands', 'HMD'), 'flags'),
SJ       ('1f1f8-1f1ef', 2372, 2, 1, '🇸🇯', ['SJ', 'flag'], ':flag_sj:', [':sj:'], ('Svalbard and Jan Mayen', 'SJM'), 'flags'),
UM       ('1f1fa-1f1f2', 2373, 2, 1, '🇺🇲', ['UM', 'flag'], ':flag_um:', [':um:'], ('United States Minor Outlying Islands', 'UMI'), 'flags'),
EA       ('1f1ea-1f1e6', 2374, 2, 1, '🇪🇦', ['EA', 'flag'], ':flag_ea:', [':ea:'], ('Ceuta & Melilla', 'MLN'), 'flags'),
CP       ('1f1ea-1f1e6', 2374, 2, 1, '🇪🇦', ['EA', 'flag'], ':flag_ea:', [':ea:'], ('Ceuta & Melilla', 'MLN'), 'flags'),
DG       ('1f1ea-1f1e6', 2374, 2, 1, '🇪🇦', ['EA', 'flag'], ':flag_ea:', [':ea:'], ('Ceuta & Melilla', 'MLN'), 'flags'),
MF       ('1f1f2-1f1eb', 2377, 2, 1, '🇲🇫', ['MF', 'flag'], ':flag_mf:', [':mf:'], ('Saint Martin (French part)', 'MAF'), 'flags'),

